# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Base
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: maikol-solis
          template: classic
          filename: metrics-base.svg
          base: header, activity, repositories
          config_timezone: America/Costa_Rica
          # ACHIEVEMENTS
          plugin_achievements: yes
          plugin_achievements_limit: 6
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
#         plugin_achievements_display: compact
          repositories: 200
          # ISO CALENDAR
          plugin_isocalendar: yes
          # LANGUAGES
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage
          
